[project]
name = "sromo1-github-io"
version = "0.1.0"
description = "Personal website for Sebastian Romo"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "jinja2>=3.1.6",
    "markdown>=3.8.2",
    "python-frontmatter>=1.1.0",
]
